---
collections:
  - name: ansible.posix
    version: 1.6.0
  - name: ansible.utils
    version: 2.12.0
  - name: community.general
    version: 7.3.0
  - name: community.sops
    version: 1.9.0
  - name: kubernetes.core
    version: 2.4.0
roles:
  - name: xanmanning.k3s
    version: v3.4.2
