ansible_become_pass: ENC[AES256_GCM,data:WlW3862JDA==,iv:etypn+85NqwFup2b9yliPCm1+R+gO7O5fBFFjgUMbFI=,tag:6/X4VPQZKuxpmR2D8bBydA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17nr093c37k5732q9ksxf2p785wd9fxjej7axzcn66lm6muys0eks9kmzts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBva1NoR21MZ211aDhOZG1O
            OHlGeFVyeFJqN2dVQS9mTkIxUlVwMTk2bVVJCktmN003LzJ2MzhxWmt6MGl6VGs1
            WWF5T01ZcFRDajh4R1NqNjFOVUI5ZnMKLS0tICtVMGp4SXRhWWZEREVNNWptLzZQ
            eURjd1RsSmFuYVpqSlRNOEFobm5nYUkKeLp0kM1o4NJpruGcQ0XLxJEz6u7I0fsj
            sflWUv9z8EsSsz73HJyrPUs/RLX/8YKMiTTCrVOQhHffh6aTmg7fdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-31T13:50:35Z"
    mac: ENC[AES256_GCM,data:sY8OOWNrGfLgQFNZmXD5xXCZ0CrH62jOTV/y18cBh9nyaZztsBwLVuBtu7d9qtXvgoHidR6YxS1NshAq1cxiJfm5RE0wNz+/meUhPVSa8UT9x42ckF1Dio4ULLPyIw8DuSRuR7Pw5Mx6yAFPSdGaUhMXmisFUGsj09y5rDOjE5c=,iv:i/k7tNjc9dq4Vi914DVR77+sNek6/RsQzFenLEGTNRA=,tag:mvuNmv1OesqYwQMWV67KkQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
