ansible_become_pass: ENC[AES256_GCM,data:h3Nn7OEt9g==,iv:ZKBLTvCADCNenSxuexb9QsdmuJGaea6ADMMKtKyWIfo=,tag:ZWPl4S1VjDLP5+j0OEyhGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17nr093c37k5732q9ksxf2p785wd9fxjej7axzcn66lm6muys0eks9kmzts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cFpBcWFPWHE3dVcxMDRU
            MFVYSzkzdWl4empCOW5yQVV4TDJSOVA3YlJ3CjhEak1ua2lkbWFkYnlCa2U3ZnZE
            L3JlZG9jQkNWMUlPZTVZTytWYWVwNVEKLS0tIDVabVJIdklXS000RHBlK3p3TXNZ
            b0lqakZwVFY0MmV2T25EYXBGRUlQVWsKIyKdkFxUb12xF1v57fAp73lgoCiQAy21
            Rn6/Ufi62NZ7sKwbaaRSBHHgoQ5GLWp05koNjf9RQJRApPFX4+ca1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-31T13:50:35Z"
    mac: ENC[AES256_GCM,data:eJLINn+sIFnetqgyCd4Hr0hGeutWHDqvon3QhyzTJ/Oi6kXdHBRGrzSW0gF585ccECbKdkaPY5sq1bJ1Uv+9OFZ3/ytsimRQo9/K2cBEiMdmhCUs18h+gUPHVLFWMZDS+mdfuWN5lMynriNpnj9uwFpkGQ/vwKctLuHDawCrmb8=,iv:nHU/4wBvELTj6mlGuiVHXvwIXln/7bugxHVITGRdO/4=,tag:1F/B7GVtjXI1hopt3O9CeQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
