---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitea-pvc
  namespace: tools
  labels:
    type: local
    app.kubernetes.io/name: gitea
    app.kubernetes.io/csi-provider: nfs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: "truenas-csi"
