---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: truenas-csi
  labels:
    substitution.flux.home.arpa/disabled: "true"
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.1.254
  share: /mnt/bigguy/nfs
  subDir: ${pvc.metadata.namespace}/${pvc.metadata.name}
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard
  - noatime
  - nfsvers=4.1
