---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: truenas
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.1.254
  share: /mnt/bigguy/nfs
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions: ["hard", "noatime"]
