---
kubernetes:
  children:
    master:
      hosts:
        k3s-pve-controller-0:
          ansible_user: ubuntu
          ansible_host: 10.4.0.40
    worker:
      hosts:
        k3s-pve-worker-0:
          ansible_user: ubuntu
          ansible_host: 10.4.0.30
        k3s-pve-worker-1:
          ansible_user: ubuntu
          ansible_host: 10.4.0.31
        k3s-pve-worker-2:
          ansible_user: ubuntu
          ansible_host: 10.4.0.32
