---
# https://rancher.com/docs/k3s/latest/en/installation/install-options/agent-config/
# https://github.com/PyratLabs/ansible-role-k3s

k3s_control_node: false
k3s_agent:
  node-ip: "{{ ansible_host }}"
  kubelet-arg:
    - eviction-minimum-reclaim=imagefs.available=10%,nodefs.available=10%
    - eviction-hard=imagefs.available<10%,nodefs.available<10%
  node-label:
    - "proxmox.k3s.cluster=true"
  # k3s_registration_address: "{{ kube_vip_addr }}"
