#!/usr/bin/env ansible-playbook
# -*- coding: utf-8 -*-
# When I wrote this, only God and I understood what I was doing
# Now, God only knows
# vim:ff=unix ts=2 sw=2 ai expandtab
---
- name: Reboot
  hosts: all
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 5 seconds...
      ansible.builtin.pause:
        seconds: 5
      delegate_to: localhost
  tasks:
    - name: Reboot
      ansible.builtin.reboot:
        msg: Rebooting nodes
        reboot_timeout: 3600
