---
apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-ep
  namespace: tools
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: harbor
        group: external
        url: https://harbor.${SECRET_DOMAIN}
        ui:
          hide-hostname: true
          hide-url: true
        interval: 1m
        client:
          dns-resolver: tcp://1.1.1.1:53
        conditions:
          - "[STATUS] == 200"
      - name: harbor
        group: guarded
        url: 1.1.1.1
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        dns:
          query-name: harbor.${SECRET_DOMAIN}
          query-type: A
        conditions:
          - "len([BODY]) == 0"
