---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-pvc
  namespace: tools
  labels:
    app.kubernetes.io/name: harbor
    app.kubernetes.io/sci-provider: nfs
spec:
  volumeName: harbor
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: "truenas-csi"
