---
# yaml-language-server: $schema=https://kubernetes-schemas.dxas90.work/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-operator
  namespace: rook-ceph
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: rook-ceph
      version: v1.12.3
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values: # https://github.com/rook/rook/blob/release-1.12/deploy/charts/rook-ceph/values.yaml
    csi:
      enableCSIHostNetwork: false
      csiAddons:
        enabled: true
      # Set when encryption/compression is enabled
      cephFSKernelMountOptions: ms_mode=secure
      nfs:
        # -- Enable the nfs csi driver
        enabled: true
    monitoring:
      enabled: true
