# https://external-secrets.io/latest/provider/fake/
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
    name: fake
    namespace: kube-system
spec:
    provider:
        fake:
            data:
                - key: ENC[AES256_GCM,data:DhTj3CpHkjt7A3UbmRMtOoGmBlIES0grvnT9oA==,iv:A7W/1y90GAi4ja9weECGRBHztJyqucGrs4sNkFnp2IM=,tag:CxgM0udRNwlQZXms4e0/Rg==,type:str]
                  value: ENC[AES256_GCM,data:D3A8Iv8ebZWPlPMT3g==,iv:vAtYbvAKLm6tlUHOHKJEQQu2A3o/oF4Rb+T7IP8G4Z8=,tag:qUVT42IFq/yyO8qc+mwBLQ==,type:str]
                  version: ENC[AES256_GCM,data:zLE=,iv:jugke1SA/AhDZ2sP30TStKTU8w3LlgOk/uxmGoNybiU=,tag:TQ5YUKkmq3p7ng4YmvtAGg==,type:str]
                - key: ENC[AES256_GCM,data:Zd8MZrQfXlqpB6d7spu8E6qh8Fj1ICR38KfqMg==,iv:qUQxejPvYaElpxauyKd5jY8gm/8ByLexiMZwAcowzbw=,tag:ry/B7e+r+1/05Z3PC1hp7w==,type:str]
                  value: ENC[AES256_GCM,data:0fCIv1oyiF5zTCNa+e3nA334u3ZWyYL2Jg==,iv:2R8i7WJLBTp1tyxYjn5uir1VKmd6iSd6xroUIrgLn9Y=,tag:BDQdP2umCLbdzrerxnLbcg==,type:str]
                  version: ENC[AES256_GCM,data:6bM=,iv:CCcdLn/JFUYykbJtO2KgejniXByvSg4XrlUrTd62flc=,tag:AQwh3uqU8y3iQT6DVZ4mkg==,type:str]
                - key: ENC[AES256_GCM,data:f2GSvBNZwAMtxMRxKtEP+LBV29qxRXjbZ+piQcmpFJe6WDoZKOJ94J2PN/4=,iv:tOxzoJY05E1nd1zpIn2+XJGsiJ2pEY7Q5uEnWNfwtSE=,tag:rPOV2Hcr0wIfjRyZYHgiig==,type:str]
                  value: ENC[AES256_GCM,data:TCpql3yeaNDVtyK2gDRI2N4ER+dyZZuws4M=,iv:kiSHfGucQIMhLm/Yc/kkofUy2xtOjCPjNrz32fKgV0M=,tag:dGI5WiRtn/ih4L2p9w4OSw==,type:str]
                  version: ENC[AES256_GCM,data:EME=,iv:jtKAyojl9hFJRwo6+pL2QTprrmod3LkeeVsa/o2pDCs=,tag:KcGMUdjp3JI/u5rlenElVw==,type:str]
                - key: ENC[AES256_GCM,data:Oht2m+l9BXhz5HcRubVv13jYsVZ917bybL0Av/MYoA==,iv:82k+tl9DQ2K/5S6ThXTRXgBMVgOA6F1gdhEc1P+seFg=,tag:B4VCBWLqIoiqVu6F1v+M/w==,type:str]
                  value: ENC[AES256_GCM,data:zRNWF3OQzBAx9u7b+yr2jvVK613XMffNStN0C21t2Gk4uSrfO1drsMmO5VRP9Sn04uw9,iv:CCbTUiZVYF9OvcwtLjT5N1OAVbN1olZr2kJuYBwLxKg=,tag:at1H4c2s6ceHAzqcL3j+Sg==,type:str]
                  version: ENC[AES256_GCM,data:8y4=,iv:dnSjXkkp7B1M4g1zVLuRhSAKJCfSUIiWOSvyi9pb1Ls=,tag:c4DGftOWbsk0RGp8VeShDg==,type:str]
                - key: ENC[AES256_GCM,data:i6mzg1hkiywlGA==,iv:alKjpKGeHZuYR6wE3gPkX8ngRae+YOWTrvy55eG/hJg=,tag:3TXGkQtYFS2oX2ez9yLvwA==,type:str]
                  valueMap:
                    foo: ENC[AES256_GCM,data:VkmA7nNgGg==,iv:g6shodaOlopta63dPBxPWERf0J7rfjHATonD5KvTrlE=,tag:LPwPY+7RcGBAoL3dSTR2jA==,type:str]
                    other: ENC[AES256_GCM,data:5M972RA=,iv:bH4W9n4d9Wt3ofCRIJCHLFAJVNn2t2TmesovzVPdgdU=,tag:jIIxmo4MA0Zhn6M8k2sjUA==,type:str]
                - key: ENC[AES256_GCM,data:+DpNVL2c5a+03zpKoPA8GEnplXU=,iv:wvi2RcguprGE9ZK1f5yk59EWghbSpHwYXKfUD6Tba14=,tag:MPfWhSmVn0ysRI7r1WH8zg==,type:str]
                  valueMap:
                    #ENC[AES256_GCM,data:U+bNsLF7pR0tj1HoARTbFxlBnfQuqvtAQJk7o/RiX9TIOL2VviektAZDnG+x,iv:fK0ZbzWX4kkEnYoKZuagjP7VrfnhOAWfOy2qETb6siE=,tag:4zcFfE9CrHWuaHa/RQXtaA==,type:comment]
                    users: ENC[AES256_GCM,data:QHzd2F38C/0VZxDeaEErRH2/CszEXhws88vKKOrLoKH4ScX+KK4WAwjL+TipSNNf0qhXzluDUNJsUZZB,iv:KcWF9EDVRgVyJMrp5czx9gmHKXi7+61nt89d26gP0+Y=,tag:iAVg3s0Tp9Yvjjz9n3xP5w==,type:str]
                    #ENC[AES256_GCM,data:F09BuIALLtCxDjmDWUVpNZc=,iv:otuT6gY+BbvQJFtOc7ezxc1EJCcV/lSYCy40fYeu+tE=,tag:zBVa+Lq57ZXi7UsA9yIgoQ==,type:comment]
                    apps: ENC[AES256_GCM,data:iIpQzKzQjw9mC1UYFnsTrzky64q99CmGbap0EK8j5kM0Qz6+GZk=,iv:QS6fEpADN0rXGRN4+CmEPxqi9lAW96rXsPfNonH2UJo=,tag:8/7ZxVsECgpZrg6I9FF+Cw==,type:str]
                    #ENC[AES256_GCM,data:ZAEsSA/u8IiS0O/DkwJUzVN5fir3fJ/GI6S+2dc3,iv:Uj126RAxvrR4NzBigqsGGECwXizyZi54yoWsQ3BOGkI=,tag:aeii7x3rPiOSbU3HP4mb3g==,type:comment]
                    services: ENC[AES256_GCM,data:c5a9uv/hFzz6YisGO1G/l1+rooq58OE1wshYQTgJZZI3dUBlON1LdIxI,iv:eGSBGLun+0dN1zSIIr3wh/3mEiP6Hnl4F7PGOv8Mk7U=,tag:1vT6Dr9x/r+yVjqEMUFcMg==,type:str]
                  version: ENC[AES256_GCM,data:RnA=,iv:2c4BoCz9X/fcCGKoI9GJyfuwxZnlCcqOKSd0nXZrFQE=,tag:nLyewsPKIE8engLz3d4jQw==,type:str]
                - key: ENC[AES256_GCM,data:G+wxBBOlHzKz0FvchO9u6GyLrhA6Q5kwQrOY0Jw=,iv:vWXm/Ier32pQkKh3GF03z9KqJOLotTlZFXXMvuFUlTs=,tag:f1wWK8DgbaQrWm0IOP6APQ==,type:str]
                  version: ENC[AES256_GCM,data:vtE=,iv:6pDUrPvJRDxT/InKSGpr88UpH8TUeCw7PkVT6dxLlTo=,tag:tpHB9JXp7ePdV4z+NHr2Jg==,type:str]
                  valueMap:
                    username: ENC[AES256_GCM,data:wKyrkh8yGIGmi0l61A==,iv:WnavJKWzmBB+BCCblzJdLTZ2FPJ0zVgpURVphAEbqrA=,tag:EjReDMsyyVu5ZVzdcgPjbw==,type:str]
                    password: ENC[AES256_GCM,data:NPhSx7a/HkPf9p+UZyX1o4+8IPg/c4AaNLBp/LTf/EzlyBEbdfC0RQOlQ6mJqQsMP10y7CC9GrAd5mUmQHwU,iv:eE67O9IRfRO2oZ+Iq9AtZYh87fBUVBJLMXLanzkYLlM=,tag:mhYMELH4ZW6yNXX+bhJU/A==,type:str]
                    init_postgres_super_pass: ENC[AES256_GCM,data:TQHqs/O7FXTJsOYw3IdpDtz6mgeMjSJbK/k0zlF9bMJ5jBDW1QvzoNeGXw38rdqoPvrdfV8mKWHW1g==,iv:1IenCqvZ2rXu4qg29wbur9XEpDPrkGTWNlOLQ82/TKc=,tag:rpcbpU8Mkg6o8ac9RjCA8w==,type:str]
                - key: ENC[AES256_GCM,data:Cx4qXWOuMu3CyXX1IcyXeHb/YV7zeTf9dGMObkS+,iv:eb0+9dVDCDUgwokBqYPu+Zpx3ua0tt1PVsJDMi9v24g=,tag:c6xGXok0qT1U+LXyM5sd6Q==,type:str]
                  version: ENC[AES256_GCM,data:wwU=,iv:1Ds4CnSEbiekndcuxLytbvUJjRODdkzzk6rxPH7T4Zg=,tag:arBjMy42GZRykss5HS0LqQ==,type:str]
                  valueMap:
                    private_key: ENC[AES256_GCM,data:gyzfAQxSaGitSN6+0KONeHCBtz6z6bFRmitbSdw8KBJxFO+rCSgOyhQj71g=,iv:1zqd4oa9XIZglUM7+Uc2LM68rBi88euCfB2zRR7h3z8=,tag:Up5eygv766JJyy53NaJwVA==,type:str]
                    preshared_key: ENC[AES256_GCM,data:bBX7xyW4iCfEUA4o4L/TzddEN4bXPC6woL1pX+NpZSkghmjeVLZWiOQPXU4=,iv:2TeZLB3RylDcA4uie6gg0PrCE20wtDmBNPcy9ph6gec=,tag:1JsYe/s6DhRLaMt0dHge2A==,type:str]
                    public_key: ENC[AES256_GCM,data:FqmUghbbesKNA4fwcNgasJUM9twvm4YkgOPMqguMT/CpiF0wv2A6A7mH+HE=,iv:NYL7PNDI4oBFJtDyW65U2Zfyswug7Y6riVxLVs2u/5M=,tag:oHWxS2zhiB9mu01zm962Qg==,type:str]
                    endpoint_ip: ENC[AES256_GCM,data:6VJFI4KkZ4FacQ6Mqw==,iv:ZCOpw+X9d3zJ4mepXfsuPAd+wOYRBQh9R/gTAk8y+8A=,tag:XAnf0/7ngj7N5LxX1T9MEg==,type:str]
                    addresses: ENC[AES256_GCM,data:KorNkuH5A5EZuMz3kQ==,iv:ckbMigoKmK7WmvGKnbia/u4vh6Tz70oiGitxAQAf3bI=,tag:NApHwR7bL++gY+zKSbleFg==,type:str]
                - key: ENC[AES256_GCM,data:ROmiq80oqdgRaM1dnzHzdnHN1660o/gAgEQm3lc=,iv:y2p6/nxWdqTmkKWKcHx/2r/5WogLCMVARWO8xao7xXA=,tag:Oed2awienvv2hEE++4sKgA==,type:str]
                  version: ENC[AES256_GCM,data:LB4=,iv:DVmmIBi5wC3EIIJQpEdnfAkq7psWXO7189lIfK8IwrI=,tag:t/+Xng3xOraJvD2DbRoBFA==,type:str]
                  valueMap:
                    ssh_key: ENC[AES256_GCM,data:egBH,iv:/eZpJEkEhmMA1qHVozQIpFZbSsrF8eR6bS7A8MBunnw=,tag:0Q7AN1rrqUGZE1O58X49pQ==,type:str]
                - key: ENC[AES256_GCM,data:4+pCAM/ASH9B9CHtpIVoGUoPlmGD+GlBVFFpYdYqKw==,iv:AO91UdYvabCLXBKQVLOazJ+u3sHcw3CfoNXMZnm6JPA=,tag:EoNwN1hyUpm7VDP91aRBmQ==,type:str]
                  value: ENC[AES256_GCM,data:BI1EzhM=,iv:p3HV7kma5LlQ9Gja/T/cnQ1lZxVeivvi/R4g+v30/8A=,tag:SChK34l/ytSqRskg2PpAFA==,type:str]
                  version: ENC[AES256_GCM,data:Nbg=,iv:nexJnYPypj74GmjbQfaVzi0PHbdcB8oqkV5n2BJJtc8=,tag:M7VwPImmS+iHeLHWkpZpPA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17nr093c37k5732q9ksxf2p785wd9fxjej7axzcn66lm6muys0eks9kmzts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Uk0ybC9jYmZvUG5HcE5P
            SUxDT1NHNUNVYXdkaUkwZG85OEJXelRZZFFZClVEMGdxM3VSK200bWRLZ0YzTThz
            VE1YZ3BhWWlnYnd4eGtPK3NqVTQxS2MKLS0tIDU5b1BzQlRka0NReTE3NGdyRWZn
            amhEREVKYjg5b21RR3UxN3pnVXhudWsKANoiMZfm+it1BCWJBa9Q7OEfy7hurmkD
            9kvojJCT9llREncLh9qhl/EzI16io7wn6vO/70ZrPMla2HzAFxwbEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-01T17:00:16Z"
    mac: ENC[AES256_GCM,data:W/js4w4TQfvBbVaRhTsId8VI2vspPhSY8d7COYuxffSIqt8YiBnwniB9wwfe2QbCT6YaDOoLdemqfy5VhT8p4JJ+3YNfuZBJ1spFGDzUwhHIDa1wIB6f9pQKkP06PNYZI4j5V9dMFsJQYtGZiSAJiJxPTgJKEaUW3rTTXQsifnc=,iv:zEGYfEEu6OqNkIy8WwNd/GuMyzPAbar4ZgYAjH6cOGQ=,tag:CIippQQ2cnEupcTsfBHnVQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|externalName|tls|rules|value|key|port|targetPort)$
    version: 3.7.3
